# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'ContainerButler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'SnapKit', '~> 4.0.0'
 pod 'Alamofire', '~> 4.5'
 pod 'RxSwift', :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
 pod 'RxCocoa',  :git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'swift4.0'
 pod 'SwiftDate', '~> 4.0'
 pod 'RxDataSources', :git => 'https://github.com/RxSwiftCommunity/RxDataSources.git', :branch => 'swift4.0'
# pod 'IQKeyboardManagerSwift', '~> 4.0.13'
 pod 'SVProgressHUD'
 pod 'Kingfisher', '~> 4.0'
 pod 'MJRefresh'
 pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-4'
end
