# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'ContainerButler' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

 pod 'SnapKit', '~> 3.2.0'
 pod 'Alamofire', '~> 4.5'
 pod 'RxSwift',    '~> 3.0'
 pod 'RxCocoa',    '~> 3.0'
 pod 'ObjectMapper', '~> 2.2'
 pod 'SwiftDate', '~> 4.0'
 pod 'RxDataSources', '~> 1.0'
 pod 'IQKeyboardManagerSwift', '4.0.10'
 pod 'SVProgressHUD'
 pod 'Kingfisher', '~> 3.0'
 pod 'MJRefresh'
end
